# Generated by Django 3.0.6 on 2020-05-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('cuil', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('fecha_nacim', models.DateField(blank=True, null=True)),
                ('viandas', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fechas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descr', models.CharField(blank=True, max_length=200, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('public', models.IntegerField()),
            ],
            options={
                'db_table': 'fechas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Liquidaciones',
            fields=[
                ('periodo', models.IntegerField(primary_key=True, serialize=False)),
                ('publica', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'liquidaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelFechas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('descr', models.CharField(blank=True, max_length=30, null=True)),
                ('habilitado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel_fechas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, max_length=6, null=True)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('bytes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recibos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoLiquidacion',
            fields=[
                ('uid', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tipo_liquidacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=30, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('salt', models.CharField(max_length=21, null=True)),
                ('password', models.CharField(max_length=60, null=True)),
                ('cuil', models.OneToOneField(db_column='cuil', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tecninfor_recibos.Empleados')),
                ('admin', models.IntegerField(blank=True, null=True)),
                ('habilitado', models.IntegerField(blank=True, null=True)),
                ('last_pwd_change', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
    ]
